const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {URL}=require('url');
const ROOT=path.join(__dirname,'public');
loadEnv(path.join(__dirname,'.env'));
const PORT=Number(process.env.PORT||4180);
const HOST=process.env.HOST||'0.0.0.0';
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg'};
const JOB_QUERIES={'행정·기획':['공공기관 경영','행정 기획 보고서'],'기계·설비':['기계설비 유지관리','시설관리 실무'],'난방·에너지':['에너지 관리 난방','탄소중립 에너지'],'환경':['환경 관리 ESG','탄소중립 공공기관'],'토목·건축':['토목 시설물 관리','건축 유지관리'],'전기·전자':['전기설비 유지관리','전기 안전'],'안전·소방':['산업안전 실무','소방 안전관리'],'전산·정보통신':['공공기관 디지털 전환','스마트시티 정보통신']};
const CERT_QUERIES={'행정·기획':['행정사 자격증 시험'],'기계·설비':['공조냉동기계기사 필기','일반기계기사 필기'],'난방·에너지':['에너지관리기사 필기','가스기사 필기'],'환경':['대기환경기사 필기','수질환경기사 필기'],'토목·건축':['토목기사 필기','건축기사 필기'],'전기·전자':['전기기사 필기','전기산업기사 필기'],'안전·소방':['산업안전기사 필기','소방설비기사 필기','위험물산업기사 필기','건설안전기사 필기'],'전산·정보통신':['정보처리기사 필기','정보통신기사 필기']};
const coverCache=new Map();
const rejectedCoverHashes=new Set([
  // 교보문고가 존재하지 않는 ISBN에도 200으로 반환하는 공통 '표지 없음' 이미지
  '538a62800ebdd59a1b98234d20c22d03bb93583c4486af2c223821d60e9eb529',
  // Google Books의 공통 '표지 없음' 이미지
  '3efa8c43e5b4348f303a528c81adf435f0111ea752fe9f0f6241478b60987fa6'
]);
const FALLBACK_BOOKS=[
  {title:'공공기관 ESG 실무 가이드',authors:['구미도시공사 AI 북큐레이터'],publisher:'연동 대기',publishedDate:'',description:'실시간 도서 API 키를 설정하면 실제 최신 도서로 자동 교체됩니다.',categories:['공공경영','ESG'],isbn:'',thumbnail:'',source:'오프라인 안내',match:90},
  {title:'스마트시티와 공공서비스 혁신',authors:['구미도시공사 AI 북큐레이터'],publisher:'연동 대기',publishedDate:'',description:'Google Books 또는 네이버 책 검색 연결 후 실제 서지정보와 표지가 표시됩니다.',categories:['스마트시티','디지털 전환'],isbn:'',thumbnail:'',source:'오프라인 안내',match:87},
  {title:'현장 시설물 안전관리 실무',authors:['구미도시공사 AI 북큐레이터'],publisher:'연동 대기',publishedDate:'',description:'도서관정보나루 키와 도서관 코드를 설정하면 소장 및 대출 상태가 함께 표시됩니다.',categories:['안전관리','시설관리'],isbn:'',thumbnail:'',source:'오프라인 안내',match:85}
];

function loadEnv(file){if(!fs.existsSync(file))return;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const match=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);if(!match||match[2]==='')continue;let value=match[2];if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);if(process.env[match[1]]===undefined)process.env[match[1]]=value;}}
function json(res,status,data){res.writeHead(status,{'Content-Type':MIME['.json'],'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data));}
function safeFile(urlPath){const requestPath=urlPath==='/'?'index.html':decodeURIComponent(urlPath).replace(/^\/+/, '');const file=path.resolve(ROOT,requestPath);return file.startsWith(ROOT+path.sep)?file:null;}
async function readBody(req){return new Promise((resolve,reject)=>{let body='';req.on('data',chunk=>{body+=chunk;if(body.length>100000){reject(new Error('요청이 너무 큽니다.'));req.destroy();}});req.on('end',()=>{try{resolve(body?JSON.parse(body):{});}catch{reject(new Error('올바른 JSON 요청이 아닙니다.'));}});req.on('error',reject);});}
function clean(text=''){return String(text).replace(/<[^>]*>/g,'').replace(/&quot;/g,'"').replace(/&amp;/g,'&').trim();}
function titleKey(text=''){return clean(text).normalize('NFKC').toLowerCase().replace(/[\s:：·ㆍ,.!?()\[\]{}'"“”‘’\-]/g,'');}
function sameBook(candidate,{title,author,publisher}){const wanted=titleKey(title),found=titleKey(candidate.title);if(!wanted||!found)return false;const titleMatch=wanted===found||(Math.min(wanted.length,found.length)>=6&&(wanted.includes(found)||found.includes(wanted)));if(!titleMatch)return false;const authorKey=titleKey(author),publisherKey=titleKey(publisher),authors=titleKey((candidate.authors||[]).join(' ')),candidatePublisher=titleKey(candidate.publisher);return !authorKey&&!publisherKey||authors.includes(authorKey)||authorKey.includes(authors)||candidatePublisher.includes(publisherKey)||publisherKey.includes(candidatePublisher);}
function isbnOf(ids=[]){for(const id of ids){if(id.type==='ISBN_13')return id.identifier;}return ids[0]?.identifier||'';}
function normalizeGoogle(item){const v=item.volumeInfo||{},thumbnail=(v.imageLinks?.thumbnail||'').replace(/^http:/,'https:');return {id:'g:'+item.id,title:clean(v.title),authors:v.authors||[],publisher:v.publisher||'',publishedDate:v.publishedDate||'',pageCount:Number(v.pageCount||0),description:clean(v.description||''),categories:v.categories||[],isbn:isbnOf(v.industryIdentifiers),thumbnail,source:'Google Books'};}
function normalizeNaver(item,index){return {id:'n:'+item.isbn+index,title:clean(item.title),authors:clean(item.author).split('^').filter(Boolean),publisher:clean(item.publisher),publishedDate:item.pubdate?`${item.pubdate.slice(0,4)}-${item.pubdate.slice(4,6)}-${item.pubdate.slice(6,8)}`:'',description:clean(item.description),categories:[],isbn:(item.isbn||'').split(' ').pop(),thumbnail:item.image||'',source:'네이버 책'};}
function normalizeYes24(item){const content=item.contentDetail||{},description=clean([content.bookIntroduction,content.bookSummary].filter(Boolean).join(' '));return {id:`y:${item.itemId}`,title:clean(item.title),authors:clean(item.author).split(/[,;|]/).map(v=>v.trim()).filter(Boolean),publisher:clean(item.publisher),publishedDate:item.publishDate||'',pageCount:Number(item.pages||0),description,categories:[item.goodsType,item.goodsSortNm].filter(Boolean),isbn:String(item.isbn13||item.isbn10||''),thumbnail:item.cover||'',tableOfContents:clean(content.tableOfContents||''),storeLinks:{yes24:item.link||item.addOnLink||''},source:'YES24'};}
async function fetchJson(url,options={},timeout=9000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const res=await fetch(url,{...options,signal:controller.signal});if(!res.ok)throw new Error(`${res.status} ${res.statusText}`);return await res.json();}finally{clearTimeout(timer);}}
async function kyoboCoverByTitle(title){if(!title)return '';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);try{const url=`https://search.kyobobook.co.kr/search?keyword=${encodeURIComponent(title)}`,res=await fetch(url,{signal:controller.signal,headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/127 Safari/537.36'}});if(!res.ok)return '';const html=await res.text(),wanted=titleKey(title);for(const match of html.matchAll(/<input\b[^>]*\bdata-bid="([0-9X]+)"[^>]*\bdata-name="([^"]+)"[^>]*>/gi)){const bid=match[1],name=match[2].replace(/&[^;]+;/g,' ');const found=titleKey(name);if(wanted===found||(Math.min(wanted.length,found.length)>=6&&(wanted.includes(found)||found.includes(wanted))))return `https://contents.kyobobook.co.kr/sih/fit-in/400x0/pdt/${bid}.jpg`;}return '';}finally{clearTimeout(timer);}}
async function fetchImage(url,timeout=9000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const res=await fetch(url,{signal:controller.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/127 Safari/537.36','Accept':'image/avif,image/webp,image/png,image/jpeg,image/*;q=0.8','Referer':new URL(url).origin+'/'}});const type=(res.headers.get('content-type')||'').split(';')[0];if(!res.ok||!type.startsWith('image/'))throw new Error('not image');const declared=Number(res.headers.get('content-length')||0);if(declared>5000000)throw new Error('image too large');const buffer=Buffer.from(await res.arrayBuffer());if(buffer.length<800||buffer.length>5000000)throw new Error('invalid image size');const hash=crypto.createHash('sha256').update(buffer).digest('hex');if(rejectedCoverHashes.has(hash))throw new Error('placeholder image');return {buffer,type};}finally{clearTimeout(timer);}}
async function resolveCover(isbn,metadata={}){const cacheKey=`${isbn}:${titleKey(metadata.title)}`;if(coverCache.has(cacheKey))return coverCache.get(cacheKey);const urls=[];if(process.env.NAVER_CLIENT_ID&&process.env.NAVER_CLIENT_SECRET){try{const books=await naverBooks(isbn);if(books[0]?.thumbnail)urls.push(books[0].thumbnail);}catch{}}try{const books=await googleBooks(`isbn:${isbn}`);if(books[0]?.thumbnail)urls.push(books[0].thumbnail);}catch{}if(metadata.title){try{const kyoboCover=await kyoboCoverByTitle(metadata.title);if(kyoboCover)urls.push(kyoboCover);}catch{}}urls.push(`https://contents.kyobobook.co.kr/sih/fit-in/400x0/pdt/${isbn}.jpg`,`https://books.google.com/books/content?vid=ISBN${isbn}&printsec=frontcover&img=1&zoom=2&source=gbs_api`,`https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg?default=false`);if(metadata.title){if(process.env.NAVER_CLIENT_ID&&process.env.NAVER_CLIENT_SECRET){try{const match=(await naverBooks(metadata.title)).find(book=>sameBook(book,metadata)&&book.thumbnail);if(match)urls.push(match.thumbnail);}catch{}}try{const match=(await googleBooks(`intitle:${metadata.title}`)).find(book=>sameBook(book,metadata)&&book.thumbnail);if(match)urls.push(match.thumbnail);}catch{}}for(const url of [...new Set(urls)]){try{const image=await fetchImage(url);coverCache.set(cacheKey,image);if(coverCache.size>300)coverCache.delete(coverCache.keys().next().value);return image;}catch{}}return null;}
async function googleBooks(query){const url=new URL('https://www.googleapis.com/books/v1/volumes');url.searchParams.set('q',query);url.searchParams.set('printType','books');url.searchParams.set('orderBy','newest');url.searchParams.set('langRestrict','ko');url.searchParams.set('maxResults','20');if(process.env.GOOGLE_BOOKS_API_KEY)url.searchParams.set('key',process.env.GOOGLE_BOOKS_API_KEY);const data=await fetchJson(url);return (data.items||[]).map(normalizeGoogle).filter(b=>b.title);}
async function naverBooks(query){if(!process.env.NAVER_CLIENT_ID||!process.env.NAVER_CLIENT_SECRET)return [];const url=new URL('https://openapi.naver.com/v1/search/book.json');url.searchParams.set('query',query);url.searchParams.set('display','20');url.searchParams.set('sort','date');const data=await fetchJson(url,{headers:{'X-Naver-Client-Id':process.env.NAVER_CLIENT_ID,'X-Naver-Client-Secret':process.env.NAVER_CLIENT_SECRET}});return (data.items||[]).map(normalizeNaver);}
async function yes24Books(query){if(!process.env.YES24_API_KEY)return [];const url=new URL('https://apis.yes24.com/v1/goods/itemList');url.searchParams.set('query',query);url.searchParams.set('category','BOOK');url.searchParams.set('sort','RELATION');url.searchParams.set('page','1');url.searchParams.set('pageSize','40');url.searchParams.set('detail','Y');try{const data=await fetchJson(url,{headers:{'X-Api-Key':process.env.YES24_API_KEY}});return (data.data?.items||[]).filter(item=>item.adultYn!=='Y').map(normalizeYes24);}catch(error){if(/^404\b/.test(error.message))return [];throw error;}}
function mergeBook(target,source){return {...target,authors:target.authors?.length?target.authors:source.authors,publisher:target.publisher||source.publisher,publishedDate:target.publishedDate||source.publishedDate,pageCount:target.pageCount||source.pageCount,description:(source.description||'').length>(target.description||'').length?source.description:target.description,categories:[...new Set([...(target.categories||[]),...(source.categories||[])])],thumbnail:target.thumbnail||source.thumbnail,tableOfContents:target.tableOfContents||source.tableOfContents,storeLinks:{...(target.storeLinks||{}),...(source.storeLinks||{})},sources:[...new Set([...(target.sources||[target.source]),...(source.sources||[source.source])].filter(Boolean))]};}
function dedupe(books){const byKey=new Map(),result=[];for(const book of books){const key=book.isbn||book.title.replace(/\s/g,'').toLowerCase();if(!key)continue;if(byKey.has(key)){const index=byKey.get(key);result[index]=mergeBook(result[index],book);}else{byKey.set(key,result.length);result.push({...book,sources:[book.source].filter(Boolean)});}}return result;}
function baseScore(book,profile){const haystack=`${book.title} ${book.description} ${book.tableOfContents||''} ${(book.categories||[]).join(' ')}`.toLowerCase();const tokens=[...profile.jobs,...profile.purposes].flatMap(v=>v.split(/[·\s]/)).filter(v=>v.length>1);const hits=tokens.filter(t=>haystack.includes(t.toLowerCase())).length;const year=Number((book.publishedDate||'').slice(0,4));return Math.min(97,72+hits*6+(year>=new Date().getFullYear()-2?5:0));}
async function aiRank(books,profile){if(!process.env.OPENAI_API_KEY)return books.map(b=>({...b,match:baseScore(b,profile),reason:`${profile.jobs.join('·')} 업무와 ${profile.purposes.join('·')} 목적에 참고할 수 있는 최신 도서입니다.`})).sort((a,b)=>b.match-a.match);
  const candidates=books.slice(0,30).map((b,index)=>({index,title:b.title,authors:b.authors,description:b.description.slice(0,700),tableOfContents:(b.tableOfContents||'').slice(0,1200),categories:b.categories,publishedDate:b.publishedDate,pageCount:b.pageCount||0}));
  const schema={type:'object',properties:{recommendations:{type:'array',items:{type:'object',properties:{index:{type:'integer'},score:{type:'integer'},reason:{type:'string'}},required:['index','score','reason'],additionalProperties:false}}},required:['recommendations'],additionalProperties:false};
  const payload={model:process.env.OPENAI_MODEL||'gpt-5-mini',store:false,instructions:'구미도시공사 임직원용 북큐레이터다. 제공된 실제 후보 도서만 선택한다. 직렬 업무 적용성, 목적, 난이도, 최신성을 평가한다. reason은 한국어 1~2문장, score는 70~99 정수다. 법령·기술 기준은 개정 여부 확인이 필요하다고 신중하게 표현한다.',input:JSON.stringify({profile,candidates}),text:{format:{type:'json_schema',name:'book_recommendations',strict:true,schema}}};
  const data=await fetchJson('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)},30000);const parsed=JSON.parse(data.output_text||'{}');const ranked=(parsed.recommendations||[]).map(r=>candidates[r.index]?{...books[r.index],match:Math.max(70,Math.min(99,r.score)),reason:r.reason}:null).filter(Boolean);return ranked.length?ranked:books;
}
async function latestStoreBooks(){const queries=['경영 신간','기술 신간','환경 신간'];const batches=await Promise.allSettled(queries.flatMap(q=>[googleBooks(q),naverBooks(q),yes24Books(q)]));return dedupe(batches.filter(r=>r.status==='fulfilled').flatMap(r=>r.value)).filter(b=>b.title&&b.isbn).sort((a,b)=>String(b.publishedDate).localeCompare(String(a.publishedDate))).slice(0,12);}
async function newBooks(){try{return {books:(await latestStoreBooks()).slice(0,20)};}catch{return {books:[]};}}
async function recommend(profile){const certification=profile.purposes?.includes('자격증·시험');const queries=certification?(profile.jobs||[]).flatMap(j=>CERT_QUERIES[j]||[`${j} 자격증`]).slice(0,6):(profile.jobs||[]).slice(0,3).flatMap(j=>JOB_QUERIES[j]||[j]).slice(0,4);if(!certification&&profile.purposes?.includes('리더십'))queries.push('공공기관 리더십');if(!certification&&profile.purposes?.includes('보고서·기획'))queries.push('기획 보고서 작성');const requests=queries.slice(0,6).flatMap(q=>[googleBooks(q),naverBooks(q),yes24Books(q)]);const batches=await Promise.allSettled(requests);let books=dedupe(batches.filter(r=>r.status==='fulfilled').flatMap(r=>r.value)).filter(b=>b.title&&(!certification||/(기사|산업기사|기능사|자격|필기|실기|기출)/.test(b.title))).slice(0,90);if(!books.length)return FALLBACK_BOOKS.map(book=>({...book,reason:`현재 외부 도서 API가 연결되지 않아 안내용 결과를 표시합니다. .env에 API 키를 등록하면 ${profile.jobs.join('·')} 분야의 실제 최신 도서를 추천합니다.`}));books=await aiRank(books,profile);return books.slice(0,30);}
function status(){return [{name:'Google Books',connected:Boolean(process.env.GOOGLE_BOOKS_API_KEY)},{name:'네이버 책',connected:Boolean(process.env.NAVER_CLIENT_ID&&process.env.NAVER_CLIENT_SECRET)},{name:'YES24',connected:Boolean(process.env.YES24_API_KEY)},{name:'OpenAI',connected:Boolean(process.env.OPENAI_API_KEY)}];}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&url.pathname==='/api/status')return json(res,200,{services:status()});if(req.method==='GET'&&url.pathname==='/api/cover'){const isbn=(url.searchParams.get('isbn')||'').replace(/[^0-9X]/gi,'');if(!/^\d{10}(\d{3})?$/.test(isbn))return json(res,400,{error:'올바른 ISBN이 아닙니다.'});const metadata={title:(url.searchParams.get('title')||'').slice(0,200),author:(url.searchParams.get('author')||'').slice(0,120),publisher:(url.searchParams.get('publisher')||'').slice(0,120)};const image=await resolveCover(isbn,metadata);if(!image)return json(res,404,{error:'표지를 찾지 못했습니다.'});res.writeHead(200,{'Content-Type':image.type,'Content-Length':image.buffer.length,'Cache-Control':'public, max-age=604800','X-Content-Type-Options':'nosniff'});return res.end(image.buffer);}if(req.method==='GET'&&url.pathname==='/api/new-books')return json(res,200,await newBooks());if(req.method==='POST'&&url.pathname==='/api/recommend'){const profile=await readBody(req);if(!Array.isArray(profile.jobs)||!profile.jobs.length)return json(res,400,{error:'업무 분야를 선택해 주세요.'});return json(res,200,{books:await recommend(profile),generatedAt:new Date().toISOString()});}if(req.method!=='GET')return json(res,405,{error:'지원하지 않는 요청입니다.'});const file=safeFile(url.pathname);if(!file||!fs.existsSync(file)||fs.statSync(file).isDirectory())return json(res,404,{error:'페이지를 찾을 수 없습니다.'});res.writeHead(200,{'Content-Type':MIME[path.extname(file).toLowerCase()]||'application/octet-stream','X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(res);}catch(error){console.error(error);if(!res.headersSent)json(res,500,{error:error.name==='AbortError'?'외부 서비스 응답 시간이 초과되었습니다.':error.message||'서버 오류가 발생했습니다.'});}});
server.listen(PORT,HOST,()=>console.log(`AI 북큐레이터 웹사이트가 ${HOST}:${PORT}에서 실행 중입니다.`));
