const JOB_TREE={
  '행정·기획':['공공기관 경영 혁신','정책 기획','보고서 작성','조직문화 리더십','데이터 기반 행정','지방공기업 ESG'],
  '기계·설비':['기계설비 유지관리','시설관리 실무','설비 예방정비','공조냉동','스마트 시설관리','기계 안전'],
  '난방·에너지':['에너지 관리','탄소중립 에너지','신재생에너지','열관리','에너지 효율','기후위기 대응'],
  '환경':['환경 관리 ESG','탄소중립','자원순환','수질 관리','대기환경','생태환경'],
  '토목·건축':['토목 시설물 관리','건축 유지관리','도시계획','스마트시티','건설 안전','공공공간 디자인'],
  '전기·전자':['전기회로 실험','회로이론 전자기학','전기설비 실무','전력 시스템 송배전','전기 교양 상식','반도체 전자공학','배터리 전력전자','자동제어 스마트그리드'],
  '안전·소방':['산업안전 실무','소방 안전관리','재난 대응','위험성평가','중대재해 예방','안전문화'],
  '전산·정보통신':['공공기관 디지털 전환','인공지능 업무 활용','정보보안','데이터 분석','스마트시티 정보통신','클라우드']
};
const PURPOSE_TREE={
  '실무 문제 해결':['실무 가이드','현장 사례','문제 해결'],
  '신기술·동향':['최신 기술 트렌드','미래 전망','혁신 사례'],
  '리더십':['리더십','조직관리','소통'],
  '보고서·기획':['기획 보고서','논리적 글쓰기','데이터 시각화'],
  '교양·인사이트':['인문 교양','사회 변화','과학 교양'],
  '자격증·시험':['기사 필기 기출','산업기사 실기','자격증 핵심이론']
};
const CERT_TREE={
  '행정·기획':['행정사 시험'],
  '기계·설비':['일반기계기사','공조냉동기계기사','설비보전기사'],
  '난방·에너지':['에너지관리기사','가스기사','신재생에너지발전설비기사'],
  '환경':['대기환경기사','수질환경기사','폐기물처리기사'],
  '토목·건축':['토목기사','건축기사','건설안전기사'],
  '전기·전자':['전기기사','전기산업기사','소방설비기사 전기'],
  '안전·소방':['산업안전기사','건설안전기사','위험물산업기사','소방설비기사'],
  '전산·정보통신':['정보처리기사','정보통신기사','정보보안기사']
};
const JOB_TERMS={'행정·기획':['행정','기획','정책','공공기관','공기업','경영','조직','보고서','리더십','의사결정','데이터'],'기계·설비':['기계','설비','시설관리','정비','공조','냉동'],'난방·에너지':['난방','에너지','열관리','가스','탄소중립','신재생'],'환경':['환경','생태','기후','탄소','수질','대기','폐기물','자원순환'],'토목·건축':['토목','건축','건설','도시','시설물','스마트시티'],'전기·전자':['전기','전자','전력','회로','전자기','반도체','배터리','송배전','제어','모터','스마트그리드'],'안전·소방':['안전','소방','재난','위험성','중대재해','산업기사','위험물'],'전산·정보통신':['전산','정보통신','디지털','인공지능','AI','데이터','보안','클라우드','소프트웨어']};
const EXAM_TITLE=/(기사|산업기사|기능사|자격증|필기|실기|기출)/;
const REJECTED_COVER_HASHES=new Set(['538a62800ebdd59a1b98234d20c22d03bb93583c4486af2c223821d60e9eb529','3efa8c43e5b4348f303a528c81adf435f0111ea752fe9f0f6241478b60987fa6']);

const clean=(text='')=>String(text).replace(/<[^>]*>/g,'').replace(/&quot;/g,'"').replace(/&amp;/g,'&').trim();
const isbnOf=(ids=[])=>ids.find(id=>id.type==='ISBN_13')?.identifier||ids[0]?.identifier||'';
function normalizeGoogle(item,branch){const v=item.volumeInfo||{};return {id:`g:${item.id}`,title:clean(v.title),authors:v.authors||[],publisher:v.publisher||'',publishedDate:v.publishedDate||'',pageCount:Number(v.pageCount||0),description:clean(v.description||''),categories:v.categories||[],isbn:isbnOf(v.industryIdentifiers),thumbnail:(v.imageLinks?.thumbnail||'').replace(/^http:/,'https:'),source:'Google Books',branch};}
function normalizeNaver(item,index,branch){return {id:`n:${item.isbn}:${index}`,title:clean(item.title),authors:clean(item.author).split('^').filter(Boolean),publisher:clean(item.publisher),publishedDate:item.pubdate?`${item.pubdate.slice(0,4)}-${item.pubdate.slice(4,6)}-${item.pubdate.slice(6,8)}`:'',pageCount:0,description:clean(item.description),categories:[],isbn:(item.isbn||'').split(' ').pop(),thumbnail:item.image||'',source:'네이버 책',branch};}
function normalizeYes24(item,branch){const content=item.contentDetail||{},description=clean([content.bookIntroduction,content.bookSummary].filter(Boolean).join(' ')),tableOfContents=clean(content.tableOfContents||'');return {id:`y:${item.itemId}`,title:clean(item.title),authors:clean(item.author).split(/[,;|]/).map(v=>v.trim()).filter(Boolean),publisher:clean(item.publisher),publishedDate:item.publishDate||'',pageCount:Number(item.pages||0),description,categories:[item.goodsType,item.goodsSortNm].filter(Boolean),isbn:String(item.isbn13||item.isbn10||''),thumbnail:item.cover||'',tableOfContents,storeLinks:{yes24:item.link||item.addOnLink||''},source:'YES24',branch};}
async function google(query,env,startIndex=0){const url=new URL('https://www.googleapis.com/books/v1/volumes');url.searchParams.set('q',query);url.searchParams.set('printType','books');url.searchParams.set('langRestrict','ko');url.searchParams.set('maxResults','40');url.searchParams.set('startIndex',String(startIndex));if(env.GOOGLE_BOOKS_API_KEY)url.searchParams.set('key',env.GOOGLE_BOOKS_API_KEY);const res=await fetch(url);if(!res.ok)throw new Error(`Google ${res.status}`);const data=await res.json();return (data.items||[]).map(item=>normalizeGoogle(item,query));}
async function naver(query,env,start=1){if(!env.NAVER_CLIENT_ID||!env.NAVER_CLIENT_SECRET)return [];const url=new URL('https://openapi.naver.com/v1/search/book.json');url.searchParams.set('query',query);url.searchParams.set('display','40');url.searchParams.set('start',String(start));url.searchParams.set('sort','sim');const res=await fetch(url,{headers:{'X-Naver-Client-Id':env.NAVER_CLIENT_ID,'X-Naver-Client-Secret':env.NAVER_CLIENT_SECRET}});if(!res.ok)throw new Error(`Naver ${res.status}`);const data=await res.json();return (data.items||[]).map((item,index)=>normalizeNaver(item,index+start-1,query));}
async function yes24(query,env,page=1){if(!env.YES24_API_KEY)return [];const url=new URL('https://apis.yes24.com/v1/goods/itemList');url.searchParams.set('query',query);url.searchParams.set('category','BOOK');url.searchParams.set('sort','RELATION');url.searchParams.set('page',String(page));url.searchParams.set('pageSize','40');url.searchParams.set('detail','Y');const res=await fetch(url,{headers:{'X-Api-Key':env.YES24_API_KEY}});if(res.status===404)return [];if(!res.ok)throw new Error(`YES24 ${res.status}`);const data=await res.json();return (data.data?.items||[]).filter(item=>item.adultYn!=='Y').map(item=>normalizeYes24(item,query));}
async function coverUrlCandidates(isbn,title,env){const candidates=[];if(env.YES24_API_KEY&&isbn){try{const url=new URL('https://apis.yes24.com/v1/goods/itemDetail');url.searchParams.set('searchType','ISBN13');url.searchParams.set('query',isbn);url.searchParams.set('detail','N');const res=await fetch(url,{headers:{'X-Api-Key':env.YES24_API_KEY}}),data=res.ok?await res.json():null,cover=data?.data?.items?.[0]?.cover;if(cover)candidates.push(cover);}catch{}}if(env.NAVER_CLIENT_ID&&env.NAVER_CLIENT_SECRET){try{const books=await naver(isbn||title,env,1);if(books[0]?.thumbnail)candidates.push(books[0].thumbnail);}catch{}}try{const books=await google(isbn?`isbn:${isbn}`:`intitle:${title}`,env,0);for(const book of books.slice(0,5))if(book.thumbnail)candidates.push(book.thumbnail.replace(/zoom=\d/,'zoom=2'));}catch{}if(isbn)candidates.push(`https://contents.kyobobook.co.kr/sih/fit-in/400x0/pdt/${isbn}.jpg`,`https://books.google.com/books/content?vid=ISBN${isbn}&printsec=frontcover&img=1&zoom=2&source=gbs_api`,`https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg?default=false`);return [...new Set(candidates)];}
async function proxyCover(isbn,title,env){for(const url of await coverUrlCandidates(isbn,title,env)){try{const res=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; GMUC-AIBookCurator/1.0)','Accept':'image/avif,image/webp,image/png,image/jpeg,image/*;q=0.8'},redirect:'follow'}),type=(res.headers.get('content-type')||'').split(';')[0];if(!res.ok||!type.startsWith('image/'))continue;const buffer=await res.arrayBuffer();if(buffer.byteLength<800||buffer.byteLength>5000000)continue;const digest=await crypto.subtle.digest('SHA-256',buffer),hash=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');if(REJECTED_COVER_HASHES.has(hash))continue;return new Response(buffer,{headers:{'content-type':type,'cache-control':'public, max-age=604800','x-content-type-options':'nosniff'}});}catch{}}return json({error:'표지를 찾지 못했습니다.'},404);}
async function kyobo(query){const url=`https://search.kyobobook.co.kr/search?keyword=${encodeURIComponent(query)}`,res=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; GMUC-AIBookCurator/1.0)','Accept-Language':'ko-KR,ko;q=0.9'}});if(!res.ok)throw new Error(`Kyobo ${res.status}`);const html=await res.text(),segments=html.split(/<li class="prod_item">/i).slice(1,31),books=[];for(const segment of segments){const identity=segment.match(/data-bid="([0-9X]+)"\s+data-name="([^"]+)"/i);if(!identity)continue;const isbn=identity[1],title=clean(identity[2]),authors=[...segment.matchAll(/class="author(?:\s+rep)?"[^>]*>([^<]+)<\/a>/gi)].map(match=>clean(match[1])).filter(Boolean),publishBlock=segment.match(/<div class="prod_publish">([\s\S]*?)<\/div>/i)?.[1]||'',publisher=clean(publishBlock.match(/class="text"[^>]*>([^<]+)<\/a>/i)?.[1]||''),date=clean(publishBlock.match(/class="date"[^>]*>([^<]+)<\/span>/i)?.[1]||''),publishedDate=(date.match(/(20\d{2})년\s*(\d{1,2})월\s*(\d{1,2})일/)||[]).slice(1).map(v=>v.padStart(2,'0')).join('-');books.push({id:`k:${isbn}`,title,authors,publisher,publishedDate,pageCount:0,description:'',categories:[],isbn,thumbnail:`https://contents.kyobobook.co.kr/sih/fit-in/400x0/pdt/${isbn}.jpg`,source:'교보문고',branch:query});}return books;}
function buildQueries(profile){const purposes=profile.purposes||[],certification=purposes.includes('자격증·시험'),otherPurposes=purposes.filter(purpose=>purpose!=='자격증·시험'),certQueries=[],jobQueries=[],purposeQueries=[];for(const job of profile.jobs||[]){if(certification)(CERT_TREE[job]||[`${job} 자격증`]).forEach(q=>certQueries.push(q));if(!certification||otherPurposes.length)(JOB_TREE[job]||[job]).forEach(q=>jobQueries.push(q));}for(const purpose of otherPurposes)(PURPOSE_TREE[purpose]||[]).forEach(q=>purposeQueries.push(`${profile.jobs?.[0]||'공공기관'} ${q}`));return [...new Set([...certQueries,...purposeQueries,...jobQueries])].slice(0,24);}
function score(book,profile){const text=`${book.title||''} ${book.description||''} ${book.tableOfContents||''} ${book.branch||''} ${(book.categories||[]).join(' ')}`.toLowerCase(),jobHits=[...new Set((profile.jobs||[]).flatMap(job=>(JOB_TERMS[job]||[job]).filter(term=>text.includes(term.toLowerCase()))))].length,purposeHits=(profile.purposes||[]).flatMap(v=>v.split(/[·\s]/)).filter(term=>term.length>1&&text.includes(term.toLowerCase())).length,foreignDomain=Object.entries(JOB_TERMS).some(([job,terms])=>!(profile.jobs||[]).includes(job)&&terms.some(term=>text.includes(term.toLowerCase()))),year=Number((book.publishedDate||'').slice(0,4));let value=25+Math.min(48,jobHits*12)+Math.min(18,purposeHits*6);if(!jobHits)value=foreignDomain?Math.min(value,35):Math.min(value,39);if(year>=new Date().getFullYear()-3)value+=4;return Math.max(10,Math.min(98,value));}
function mergeBook(target,source){return {...target,authors:target.authors?.length?target.authors:source.authors,publisher:target.publisher||source.publisher,publishedDate:target.publishedDate||source.publishedDate,pageCount:target.pageCount||source.pageCount,description:(source.description||'').length>(target.description||'').length?source.description:target.description,categories:[...new Set([...(target.categories||[]),...(source.categories||[])])],thumbnail:target.thumbnail||source.thumbnail,tableOfContents:target.tableOfContents||source.tableOfContents,storeLinks:{...(target.storeLinks||{}),...(source.storeLinks||{})},sources:[...new Set([...(target.sources||[target.source]),...(source.sources||[source.source])].filter(Boolean))]};}
function diversify(groups,profile,limit=180){const indexByKey=new Map(),result=[],wantsCertificate=profile.purposes?.includes('자격증·시험'),queues=groups.map(group=>group.filter(book=>book.title&&book.isbn&&score(book,profile)>=40&&(wantsCertificate||!EXAM_TITLE.test(book.title))).sort((a,b)=>score(b,profile)-score(a,profile)));let cursor=0;while(result.length<limit&&queues.some(queue=>queue.length)){const queue=queues[cursor%queues.length];cursor++;const book=queue.shift();if(!book)continue;const key=book.isbn||book.title.replace(/\s/g,'').toLowerCase();if(indexByKey.has(key)){const index=indexByKey.get(key),merged=mergeBook(result[index],book);result[index]={...merged,match:score(merged,profile)};continue;}indexByKey.set(key,result.length);result.push({...book,sources:[book.source].filter(Boolean),match:score(book,profile),reason:`${book.branch} 검색 가지에서 찾은 도서로, ${profile.jobs.join('·')} 업무와 ${profile.purposes.join('·')} 목적을 함께 고려했습니다.`});}return result;}
async function recommend(profile,env){const queries=buildQueries(profile),settled=await Promise.allSettled(queries.flatMap(query=>[google(query,env,0),google(query,env,40),naver(query,env,1),naver(query,env,41),yes24(query,env,1),yes24(query,env,2)])),groups=settled.filter(result=>result.status==='fulfilled'&&result.value.length).map(result=>result.value);if(groups.flat().length<120){const kyoboResults=await Promise.allSettled(queries.slice(0,10).map(kyobo));groups.push(...kyoboResults.filter(result=>result.status==='fulfilled'&&result.value.length).map(result=>result.value));}return {books:diversify(groups,profile,300),queries,generatedAt:new Date().toISOString()};}
async function newBooks(env){const queries=['2026 신간','공공기관 경영 신간','기술 트렌드 신간','환경 ESG 신간','인문 교양 신간'];const groups=(await Promise.allSettled(queries.flatMap(query=>[google(query,env,0),google(query,env,40),naver(query,env,1),naver(query,env,41),yes24(query,env,1),yes24(query,env,2)]))).filter(result=>result.status==='fulfilled').map(result=>result.value);return {books:diversify(groups,{jobs:['신간'],purposes:['최신 도서']},60)};}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});

export class RankingStore {
  constructor(ctx){this.sql=ctx.storage.sql;ctx.blockConcurrencyWhile(async()=>{this.sql.exec(`CREATE TABLE IF NOT EXISTS favorites (user_id TEXT NOT NULL,book_key TEXT NOT NULL,title TEXT NOT NULL,authors TEXT NOT NULL,publisher TEXT NOT NULL,published_date TEXT NOT NULL,isbn TEXT NOT NULL,thumbnail TEXT NOT NULL,created_at INTEGER NOT NULL DEFAULT (unixepoch()),PRIMARY KEY(user_id,book_key));CREATE INDEX IF NOT EXISTS favorites_book_idx ON favorites(book_key);`);});}
  async fetch(request){const url=new URL(request.url);if(request.method==='POST'&&url.pathname==='/favorite'){const body=await request.json(),userId=String(body.userId||'').slice(0,120),book=body.book||{},key=String(book.isbn||book.title||'').slice(0,200);if(!userId||!key||!book.title)return json({error:'필수 정보가 없습니다.'},400);if(body.saved){this.sql.exec('INSERT OR IGNORE INTO favorites(user_id,book_key,title,authors,publisher,published_date,isbn,thumbnail) VALUES(?,?,?,?,?,?,?,?)',userId,key,String(book.title).slice(0,300),JSON.stringify(book.authors||[]),String(book.publisher||'').slice(0,200),String(book.publishedDate||book.year||'').slice(0,30),String(book.isbn||'').slice(0,20),String(book.thumbnail||'').slice(0,1000));}else this.sql.exec('DELETE FROM favorites WHERE user_id=? AND book_key=?',userId,key);return json({ok:true});}if(request.method==='GET'&&url.pathname==='/shelf'){const userId=String(url.searchParams.get('userId')||'').slice(0,120),rows=[...this.sql.exec('SELECT title,authors,publisher,published_date,isbn,thumbnail FROM favorites WHERE user_id=? ORDER BY created_at DESC',userId)];return json({books:rows.map(row=>({title:row.title,authors:JSON.parse(row.authors||'[]'),publisher:row.publisher,publishedDate:row.published_date,isbn:row.isbn,thumbnail:row.thumbnail}))});}if(request.method==='GET'&&url.pathname==='/rankings'){const rows=[...this.sql.exec(`SELECT book_key,title,authors,publisher,published_date,isbn,thumbnail,COUNT(*) AS favorite_count FROM favorites GROUP BY book_key ORDER BY favorite_count DESC,MAX(created_at) DESC LIMIT 100`)];return json({books:rows.map(row=>({title:row.title,authors:JSON.parse(row.authors||'[]'),publisher:row.publisher,publishedDate:row.published_date,isbn:row.isbn,thumbnail:row.thumbnail,favoriteCount:Number(row.favorite_count),match:Math.min(99,70+Number(row.favorite_count))}))});}return json({error:'Not found'},404);}
}

function rankingStub(env){const id=env.RANKINGS.idFromName('global-book-ranking');return env.RANKINGS.get(id);}

export default {async fetch(request,env){const url=new URL(request.url);try{if(request.method==='GET'&&url.pathname==='/api/cover'){const isbn=(url.searchParams.get('isbn')||'').replace(/[^0-9X]/gi,''),title=(url.searchParams.get('title')||'').slice(0,200);if(!isbn&&!title)return json({error:'ISBN 또는 제목이 필요합니다.'},400);return proxyCover(isbn,title,env);}if(url.pathname==='/api/rankings')return rankingStub(env).fetch(new Request('https://rankings.internal/rankings',{method:'GET'}));if(url.pathname==='/api/shelf'){const target=new URL('https://rankings.internal/shelf');target.searchParams.set('userId',url.searchParams.get('userId')||'');return rankingStub(env).fetch(new Request(target));}if(url.pathname==='/api/favorite'&&request.method==='POST'){const body=await request.text();return rankingStub(env).fetch(new Request('https://rankings.internal/favorite',{method:'POST',headers:{'content-type':'application/json'},body}));}if(request.method==='POST'&&url.pathname==='/api/recommend'){const profile=await request.json();if(!Array.isArray(profile.jobs)||!profile.jobs.length)return json({error:'업무 분야를 선택해 주세요.'},400);return json(await recommend(profile,env));}if(request.method==='GET'&&url.pathname==='/api/new-books')return json(await newBooks(env));if(request.method==='GET'&&url.pathname==='/api/status')return json({services:[{name:'Google Books',connected:true},{name:'네이버 책',connected:Boolean(env.NAVER_CLIENT_ID&&env.NAVER_CLIENT_SECRET)},...(env.YES24_API_KEY?[{name:'YES24',connected:true}]:[])]});return env.ASSETS.fetch(request);}catch(error){return json({error:error.message||'요청 처리 중 오류가 발생했습니다.'},500);}}};
